version: '3.7'
services:
  mysql:
    image: mysql:8.0.20
    container_name: mysql-mychatbot
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test-mychatbot
      MYSQL_USER: root
      MYSQL_PASSWORD: test
      TZ: 'Asia/Tokyo'
    command: >
      mysqld --default-authentication-plugin=mysql_native_password
    volumes:
    - ./data/data:/var/lib/mysql
    ports:
    - 3306:3306

  app:
    build: .
    environment:
      OPENAI_API_TYPE: azure
      OPENAI_API_BASE: https://azure-openai-aa-dev.openai.azure.com/
      OPENAI_API_VERSION: {version}
      OPENAI_API_KEY: {KEY number}
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - mysql

volumes:
  data: